[package]
name = "sylph-verifier"
version = "0.1.0"
authors = ["Lymia Aluysia <lymia@lymiahugs.com>"]

[profile.release]
opt-level = 3
lto = true

[profile.bench]
opt-level = 3
lto = true

[dependencies]
byteorder = "1.1"
constant_time_eq = "0.1"
error-chain = { version = "0.11", git = "https://github.com/Lymia/error-chain.git", branch = "optimize-for-size" }
hmac = "0.4"
libc = "0.2"
lz4-sys = "1.8"
rusqlite = "0.13"
serenity = "0.4"
sha2 = "0.6"
uuid = { version = "0.5", features = ["v4"] }
