[package]
name = "sylph-verifier"
version = "0.1.0"
authors = ["Lymia Aluysia <lymia@lymiahugs.com>"]
build = "build.rs"

[profile.release]
opt-level = 3
lto = true

[profile.bench]
opt-level = 3
lto = true

[dependencies]
byteorder = "1.1"
constant_time_eq = "0.1"
diesel = { version = "0.16", features = ["sqlite"] }
diesel_codegen = { version = "0.16", features = ["sqlite"] }
dotenv = "0.9"
error-chain = { version = "0.11", git = "https://github.com/Lymia/error-chain.git", branch = "optimize-for-size" }
fs2 = "0.4"
hmac = "0.4"
libc = "0.2"
log = "0.3"
lz4-sys = "1.8"
parking_lot = { version = "0.5", features = ["nightly"] }
rusqlite = { version = "0.12", features = ["bundled"] }
serenity = "0.4"
sha2 = "0.6"
thread_local = "0.3"
uuid = { version = "0.5", features = ["v4"] }

[build-dependencies]
git2 = "0.6"
